[package]
name = "everybody_codes"
version = "0.1.0"
edition = "2024"

[dependencies]
num-complex = "0.4.6"
rayon = "1.11.0"
wide = "0.8.1"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "events_bench"
harness = false