max_width = 120
use_small_heuristics = "Off"
fn_call_width=80
attr_fn_like_width=100
struct_lit_width=60
struct_variant_width=80
array_width=100
chain_width=100
single_line_if_else_max_width=100
single_line_let_else_max_width=100